/** Presentation only; never changes field values, masks, or scale normalization. */
export const OCEAN_VISUAL_CONFIG = {
  backgroundCenter: "#07131e",
  backgroundEdge: "#02060b",
  vignetteStrength: 0.12,
  haloIntensity: 1.18,
  emissiveIntensity: 0.175,
  oceanGlowStrength: 1.08,
  outlineOpacity: 0.40,
  normalOutlineColor: 0xd5e6f2,
  selectedOutlineColor: 0x16bbff,
  selectedOutlineIntensity: 1,
  selectedOutlineRadius: 0.035,
  selectedFrameGlow: 0.12,
  cornerOpacity: 0.35,
  terrainKeyIntensity: 2.8,
  terrainRimIntensity: 1.9,
  terrainAmbientIntensity: 1.8,
  probeLineWidth: 0.10,
  probeLineOpacity: 0.42,
  probeGlowIntensity: 0.14,
  probeColor: 0x21ddff,
  labelOffsetDistance: 5.3,
  legendSeparatorOpacity: 0.45,
  legendPosition: [34, -12, 11] as const,
} as const;
