import { readFileSync } from "node:fs";
import { describe, it, expect } from "vitest";
import { adaptReplay, type ReplayPayload } from "../field/replayAdapter";
import {
  DEPTHS,
  offset,
  profile,
  resolve,
  slice,
  validateField,
} from "../field/contract";
import {
  planeGeometry,
  depthPoints,
  position,
  landGeometry,
  coastlineGeometry,
  skirtGeometry,
  layerLayout,
  visibleLevels,
  frameGeometry,
  depthY,
} from "../field/geometry";
import { rangeFor, fieldRange, color } from "../field/colors";
import { profileCsv } from "../field/exports";
// Real fixture generated by scripts/poc/verify_transport.py. Outside shipped src/assets.
const payload: ReplayPayload = JSON.parse(
  readFileSync("../outputs/phase7b/test-field.json", "utf8"),
);
const f = adaptReplay(payload).field;
describe("authoritative replay adapter", () => {
  it("validates the full canonical contract", () => {
    expect(validateField(f)).toBe(f);
    expect(f.depths).toEqual(DEPTHS);
    expect(f.effectiveDate).toBe("2021-06-15");
  });
  it.each(DEPTHS.map((d, k) => [d, k]))(
    "depth %s preserves every field value",
    (_d, k) => {
      const values = slice(f, "temperature", k);
      for (let i = 0; i < values.length; i++) {
        const r = Math.floor(i / 241),
          c = i % 241;
        if (f.ocean[i] && f.inputValid[i])
          expect(values[i]).toBe(payload.temperature[r][c][k] ?? NaN);
        else expect(values[i]).toBeNaN();
      }
    },
  );
  it("profile and CSV equal the selected field column at full precision", () => {
    const s = resolve(f, 15.25, 87.75),
      rows = profile(f, s);
    expect(rows.map((r) => r.temperature)).toEqual(
      payload.temperature[s.row][s.col],
    );
    expect(profileCsv(f, s)).toContain(String(rows[7].temperature));
    expect(profileCsv(f, s)).toContain(f.provenance.l2_state_dict_sha256);
  });
  it("location rounding matches numpy argmin including ties", () => {
    expect(resolve(f, 15.125, 87.625)).toMatchObject({ row: 40, col: 170 });
    expect(resolve(f, 40, 87)).toMatchObject({
      status: "OUTSIDE_DOMAIN",
      row: -1,
    });
  });
  it("missing L0 keeps raw L2 and missing anomaly", () => {
    const i = f.temperature.findIndex(
      (t, i) => Number.isFinite(t) && !f.climatologyDefined[i],
    );
    expect(i).toBeGreaterThan(-1);
    expect(f.temperature[i]).toBe(payload.temperature.flat(2)[i]);
    expect(f.anomaly[i]).toBeNaN();
  });
  it("rejects malformed depths, axes, shapes and scientific null coercion", () => {
    expect(() =>
      adaptReplay({ ...payload, depths_m: [...DEPTHS].reverse() }),
    ).toThrow();
    expect(() =>
      adaptReplay({ ...payload, lat: payload.lat.map((x) => x + 0.01) }),
    ).toThrow();
    expect(() =>
      adaptReplay({ ...payload, temperature: payload.temperature.slice(1) }),
    ).toThrow();
    const altered = structuredClone(payload);
    altered.temperature[0][0][0] = "" as unknown as number;
    expect(() => adaptReplay(altered)).toThrow("Malformed scientific value");
  });
});
describe("shared 3D science boundary", () => {
  it("plane has exactly one unsmoothed colored cell per supported finite value", () => {
    const range = rangeFor(f, "temperature", [7]),
      g = planeGeometry(f, "temperature", 7, 700, range, "viridis");
    expect(g.cells.length).toBe(range.count);
    expect(g.positions.length).toBe(range.count * 18);
    for (const i of g.cells) {
      expect(f.ocean[i] && f.inputValid[i]).toBeTruthy();
      expect(f.temperature[i * 15 + 7]).toBe(
        payload.temperature[Math.floor(i / 241)][i % 241][7],
      );
    }
  });
  it("all layers clip to exact selected levels and preserve the nonuniform depth axis", () => {
    const g = depthPoints(
      f,
      "anomaly",
      [7, 10],
      700,
      rangeFor(f, "anomaly", [7, 10]),
      "viridis",
    );
    expect(
      new Set(Array.from(g.positions).filter((_, i) => i % 3 === 1)),
    ).toEqual(
      new Set([
        Math.fround(position(75, 17.5, 100, 700)[1]),
        Math.fround(position(75, 17.5, 200, 700)[1]),
      ]),
    );
  });
  it("renderer geometry works on a synthetic canonical field with no replay source", () => {
    const synthetic = {
      ...f,
      temperature: new Float64Array(f.temperature.length).fill(NaN),
      climatology: new Float64Array(f.temperature.length).fill(NaN),
      anomaly: new Float64Array(f.temperature.length).fill(NaN),
      ocean: new Uint8Array(f.ocean.length),
      inputValid: new Uint8Array(f.ocean.length),
      climatologyDefined: new Uint8Array(f.temperature.length),
    };
    synthetic.ocean[1000] = 1;
    synthetic.inputValid[1000] = 1;
    synthetic.temperature[1000 * 15 + 7] = 12.75;
    validateField(synthetic);
    const g = planeGeometry(
      synthetic,
      "temperature",
      7,
      700,
      rangeFor(synthetic, "temperature", [7]),
      "viridis",
    );
    expect(g.cells).toEqual([1000]);
    expect(
      profile(
        synthetic,
        resolve(synthetic, synthetic.lat[4], synthetic.lon[36]),
      )[7].temperature,
    ).toBe(12.75);
  });
  it("renderer contains no transport, network, filesystem or inference dependency", () => {
    const source = readFileSync("src/components/DepthRenderer.tsx", "utf8");
    expect(source).not.toMatch(
      /fetch\(|replayAdapter|field\/api|node:fs|replay_field|forward_from_z/,
    );
  });
});

describe("land context and the default thermal ramp", () => {
  it("land faces cover only mask cells and walls border real ocean, never the map rectangle", () => {
    const base = -3, height = 1.125;
    const land = landGeometry(f, 0, 700, height, base);
    const cos = Math.cos(17.5 * Math.PI / 180);
    const cellAt = (x: number, z: number) => {
      const r = Math.round((17.5 - z - f.lat[0]) / 0.25);
      const c = Math.round((x / cos + 75 - f.lon[0]) / 0.25);
      expect(r).toBeGreaterThanOrEqual(0);
      expect(r).toBeLessThan(f.lat.length);
      expect(c).toBeGreaterThanOrEqual(0);
      expect(c).toBeLessThan(f.lon.length);
      return r * f.lon.length + c;
    };
    const tops = new Set<number>();
    for (let q = 0; q < land.positions.length; q += 18) {
      // Opposite corners give the centre of this emitted rectangular face.
      const x = (land.positions[q] + land.positions[q + 6]) / 2;
      const z = (land.positions[q + 2] + land.positions[q + 8]) / 2;
      const nx = land.normals[q], ny = land.normals[q + 1], nz = land.normals[q + 2];
      if (ny === 1) {
        const cell = cellAt(x, z);
        expect(f.ocean[cell]).toBe(0);
        expect(tops.has(cell)).toBe(false);
        tops.add(cell);
        expect(land.positions[q + 1]).toBe(base + height);
      } else {
        expect(ny).toBe(0); // no bottom or backing face
        expect(f.ocean[cellAt(x - nx * 0.01, z - nz * 0.01)]).toBe(0);
        expect(f.ocean[cellAt(x + nx * 0.01, z + nz * 0.01)]).toBe(1);
        const ys = Array.from({ length: 6 }, (_, j) => land.positions[q + j * 3 + 1]);
        expect(Math.min(...ys)).toBe(base);
        expect(Math.max(...ys)).toBe(base + height);
      }
    }
    // Every land cell, including disconnected islands, appears exactly once.
    expect(tops.size).toBe(Array.from(f.ocean).filter(v => !v).length);
  });
  it("land is a CONSTANT-thickness slab that encodes no elevation", () => {
    const land = landGeometry(f, 0, 700);
    const landCells = Array.from(f.ocean).filter((v) => !v).length;
    expect(landCells).toBeGreaterThan(0);
    // a top face per land cell, plus a side wall only where it meets ocean
    expect(land.positions.length).toBeGreaterThanOrEqual(landCells * 18);
    expect(land.normals.length).toBe(land.positions.length);
    // The decisive assertion: exactly TWO distinct heights exist across the
    // whole landmass - the slab base and the slab top. If any cell were
    // extruded by its own elevation there would be more, so this pins that the
    // thickness is a drawing device and not a topography claim.
    const ys = new Set(
      Array.from(land.positions)
        .filter((_, i) => i % 3 === 1)
        .map((y) => Math.round(y * 1e4) / 1e4),
    );
    expect(ys.size).toBe(2);
    expect(Math.max(...ys) - Math.min(...ys)).toBeCloseTo(land.thickness, 5);
    // and it carries no colour attribute at all, so it cannot be tinted by a value
    expect("colors" in land).toBe(false);
  });
  it("no temperature-coloured cell ever falls on land", () => {
    for (const layer of ["temperature", "anomaly"] as const) {
      const g = planeGeometry(f, layer, 7, 700, rangeFor(f, layer, [7]), "thermal");
      for (const i of g.cells) expect(f.ocean[i]).toBe(1);
    }
  });
  it("the coastline traces ocean cells that touch land", () => {
    const coast = coastlineGeometry(f, 0, 700);
    expect(coast.positions.length).toBeGreaterThan(0);
    expect(coast.positions.length % 6).toBe(0); // whole line segments
  });
  it("thermal is the default ocean ramp and stays monotonic in the value axis", () => {
    const range = { min: 0, max: 30, actualMin: 0, actualMax: 30, count: 2 };
    const cold = color(2, range, "temperature");
    const warm = color(28, range, "temperature");
    expect(color(2, range, "temperature", "thermal")).toEqual(cold);
    // cold end is blue-dominant, warm end is red-dominant
    expect(cold[2]).toBeGreaterThan(cold[0]);
    expect(warm[0]).toBeGreaterThan(warm[2]);
    // an anomaly layer ignores the palette and always uses the diverging scale
    expect(color(15, range, "anomaly", "thermal")).toEqual(
      color(15, range, "anomaly", "viridis"),
    );
  });
});

describe("colour scale is comparable across depths by default", () => {
  it("the DEFAULT scale is the whole reconstruction, not the displayed slice", () => {
    const whole = fieldRange(f, "temperature");
    for (const k of [0, 7, 14]) {
      const shown = rangeFor(f, "temperature", [k]);
      // the ramp is stretched over every depth ...
      expect(shown.min).toBe(whole.min);
      expect(shown.max).toBe(whole.max);
      // ... while the reported numbers still describe what is on screen
      const onlyThisSlice = rangeFor(f, "temperature", [k], "slice");
      expect(shown.actualMin).toBe(onlyThisSlice.actualMin);
      expect(shown.actualMax).toBe(onlyThisSlice.actualMax);
      expect(shown.count).toBe(onlyThisSlice.count);
    }
  });
  it("per-slice auto-stretch is opt-in and demonstrably not comparable", () => {
    const surface = rangeFor(f, "temperature", [0], "slice");
    const deep = rangeFor(f, "temperature", [14], "slice");
    // the old behaviour: 0 m and 1000 m span totally different temperatures ...
    expect(surface.actualMin).toBeGreaterThan(deep.actualMax);
    // ... yet both used the full ramp, so identical colours meant different water
    expect(color(surface.min, surface, "temperature")).toEqual(
      color(deep.min, deep, "temperature"),
    );
    // under the default they do not
    const a = rangeFor(f, "temperature", [0]);
    expect(color(a.actualMax, a, "temperature")).not.toEqual(
      color(rangeFor(f, "temperature", [14]).actualMax, a, "temperature"),
    );
  });
  it("neither mode uses a hardcoded range - both track the field's own values", () => {
    const warmer = {
      ...f,
      temperature: f.temperature.map((t) => t + 5),
      anomaly: f.anomaly.map((a) => a + 5),
      climatology: f.climatology,
    };
    const base = fieldRange(f, "temperature");
    const shifted = fieldRange(warmer, "temperature");
    expect(shifted.min).toBeCloseTo(base.min + 5, 9);
    expect(shifted.max).toBeCloseTo(base.max + 5, 9);
  });
});

describe("the selected slice reads as a body of water", () => {
  it("the skirt gives the slice CONSTANT thickness and never encodes temperature as height", () => {
    const range = rangeFor(f, "temperature", [7]);
    const skirt = skirtGeometry(f, "temperature", 7, 700, range, "thermal");
    expect(skirt.positions.length).toBeGreaterThan(0);
    expect(skirt.colors.length).toBe(skirt.positions.length);
    // Exactly two distinct heights across the entire skirt: the slice plane and
    // one constant drop below it. A warm cell is not drawn thicker than a cold
    // one, so height carries no data.
    const ys = new Set(
      Array.from(skirt.positions)
        .filter((_, i) => i % 3 === 1)
        .map((y) => Math.round(y * 1e4) / 1e4),
    );
    expect(ys.size).toBe(2);
    expect(Math.max(...ys) - Math.min(...ys)).toBeCloseTo(skirt.thickness, 4);
    // it hugs the perimeter, so it is far cheaper than the plane it skirts
    const plane = planeGeometry(f, "temperature", 7, 700, range, "thermal");
    expect(skirt.positions.length).toBeLessThan(plane.positions.length);
  });
  it("the skirt is drawn only at the edge of the supported region", () => {
    const range = rangeFor(f, "temperature", [7]);
    const skirt = skirtGeometry(f, "temperature", 7, 700, range, "thermal");
    // every wall is a quad of two triangles => 6 vertices => 18 floats
    expect(skirt.positions.length % 18).toBe(0);
    // a field with a single supported cell has all four walls and nothing else
    const lone = {
      ...f,
      temperature: new Float64Array(f.temperature.length).fill(NaN),
      climatology: new Float64Array(f.temperature.length).fill(NaN),
      anomaly: new Float64Array(f.temperature.length).fill(NaN),
      ocean: new Uint8Array(f.ocean.length),
      inputValid: new Uint8Array(f.ocean.length),
      climatologyDefined: new Uint8Array(f.temperature.length),
    };
    lone.ocean[1000] = 1;
    lone.inputValid[1000] = 1;
    lone.temperature[1000 * 15 + 7] = 12.75;
    const one = skirtGeometry(
      lone,
      "temperature",
      7,
      700,
      rangeFor(lone, "temperature", [7]),
      "thermal",
    );
    expect(one.positions.length).toBe(4 * 18);
  });
});

describe("exploded layer stack", () => {
  const levels = [0, 4, 7, 11, 14];
  it("separation 0 is EXACTLY the true-depth layout, to the last bit", () => {
    const ys = layerLayout(f.depths, levels, 700, 0, 4.6);
    expect(ys).toEqual(levels.map((k) => depthY(f.depths[k], 700)));
  });
  it("full separation spaces the sheets evenly from the top layer", () => {
    const ys = layerLayout(f.depths, levels, 700, 1, 4.6);
    expect(ys[0]).toBeCloseTo(depthY(f.depths[levels[0]], 700), 12);
    for (let i = 1; i < ys.length; i++)
      expect(ys[i - 1] - ys[i]).toBeCloseTo(4.6, 12);
  });
  it("order is preserved at EVERY separation - deeper never rises above shallower", () => {
    for (let e = 0; e <= 1.0001; e += 0.05) {
      const ys = layerLayout(f.depths, levels, 700, e, 4.6);
      for (let i = 1; i < ys.length; i++)
        expect(ys[i]).toBeLessThanOrEqual(ys[i - 1]);
    }
  });
  it("exploding moves HEIGHT ONLY - the geographic footprint is untouched", () => {
    const range = rangeFor(f, "temperature", [7]);
    const truth = planeGeometry(f, "temperature", 7, 700, range, "thermal");
    const moved = planeGeometry(f, "temperature", 7, 700, range, "thermal", -9);
    expect(moved.cells).toEqual(truth.cells);
    expect(moved.colors).toEqual(truth.colors);
    const xz = (a: Float32Array, k: number) =>
      Array.from(a).filter((_, i) => i % 3 === k);
    expect(xz(moved.positions, 0)).toEqual(xz(truth.positions, 0));
    expect(xz(moved.positions, 2)).toEqual(xz(truth.positions, 2));
    // and every vertex sits at the requested height, nowhere else
    expect(new Set(xz(moved.positions, 1))).toEqual(new Set([-9]));
  });
  it("every layer's outline is the SAME footprint, differing only in height", () => {
    const a = frameGeometry(0, 0.6),
      b = frameGeometry(-13.8, 0.6);
    const xz = (p: Float32Array) =>
      Array.from(p).filter((_, i) => i % 3 !== 1);
    expect(xz(a.positions)).toEqual(xz(b.positions));
    // no data attribute exists on it, so it can never be tinted by a value
    expect("colors" in a).toBe(false);
  });
  it("the sheet selection keeps the band ends and always includes the selection", () => {
    for (const count of [3, 4, 5, 6, 8])
      for (const selected of [0, 3, 7, 12, 14]) {
        const picked = visibleLevels([0, 14], count, selected);
        expect(picked[0]).toBe(0);
        expect(picked.at(-1)).toBe(14);
        expect(picked).toContain(selected);
        expect(picked).toEqual([...picked].sort((x, y) => x - y));
        expect(new Set(picked).size).toBe(picked.length);
        expect(picked.length).toBeLessThanOrEqual(count + 1);
      }
  });
  it("a collapsed clip band degrades to the single level, not to an empty stack", () => {
    expect(visibleLevels([7, 7], 5, 7)).toEqual([7]);
    expect(layerLayout(f.depths, [7], 700, 1, 4.6)).toEqual([
      depthY(f.depths[7], 700),
    ]);
  });
});
